version: '2.1'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.47.0
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - 16686:16686 # https://www.jaegertracing.io/docs/1.6/getting-started/

  db:
    restart: always
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: toor
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-ptoor", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 1

  api: &base
    build:
      context: .
      args:
        GH_USER: ${GH_USER}
        GH_TOKEN: ${GH_TOKEN}
    environment:
      LOG_LEVEL: -1
      OTEL_TRACING_URL: jaeger:4317
      OTEL_TRACING_RATIO: 0.05
    command: [api]

  worker:
    <<: *base
    command: [worker]
